import pandas as pd
from typing import List, Dict, Set, Tuple
from pathlib import Path

def generate_output_dataframe(
    predictions: Dict[str, Set[str]],
    all_source1_ids: List[str]
) -> pd.DataFrame:
    """
    Constructs the final output dataframe conforming to challenge rules:
    - Exactly one row per Source 1 entity.
    - Candidate lists are semicolon-separated strings.
    - Empty candidate lists are preserved.
    - Deterministic sorting applied.
    """
    results = []
    
    for s1_id in sorted(all_source1_ids):
        cands = predictions.get(s1_id, set())
        # Deterministic ordering for candidates
        cand_str = ";".join(sorted(list(cands))) if cands else ""
        results.append({
            "source1_entity_id": s1_id,
            "candidate_entity_ids": cand_str
        })
        
    df = pd.DataFrame(results)
    return df

def write_candidate_pairs(
    candidate_dict: Dict[str, Tuple[List[str], Dict]], 
    all_source1_ids: List[str], 
    output_path: Path
):
    """Writes the raw un-thresholded candidate pairs generated by blocking."""
    preds = {s1_id: set(cands) for s1_id, (cands, _) in candidate_dict.items()}
    df = generate_output_dataframe(preds, all_source1_ids)
    df.to_csv(output_path, sep='\t', index=False)

def write_matching_results(
    predictions: Dict[str, Set[str]], 
    all_source1_ids: List[str], 
    output_path: Path
):
    """Writes the thresholded final matching predictions."""
    df = generate_output_dataframe(predictions, all_source1_ids)
    df.to_csv(output_path, sep='\t', index=False)
    
def verify_output_subset(
    matches: Dict[str, Set[str]], 
    candidates: Dict[str, Tuple[List[str], Dict]]
) -> bool:
    """Programmatically verifies that every predicted match was actually a generated candidate."""
    for s1_id, match_set in matches.items():
        if not match_set:
            continue
            
        if s1_id not in candidates:
            print(f"Error: S1 {s1_id} has matches but no candidates generated!")
            return False
            
        cand_set = set(candidates[s1_id][0])
        if not match_set.issubset(cand_set):
            invalid = match_set - cand_set
            print(f"Error: Matches {invalid} for S1 {s1_id} were NOT in candidate pairs!")
            return False
            
    return True
