import argparse
from pathlib import Path
import sys
import pandas as pd
import numpy as np
import json
import time

from src.config import TRAIN_FILES
from src.data_loader import load_train_data
from src.preprocessing import apply_preprocessing
from src.training import (
    create_entity_split, generate_training_candidates,
    build_ground_truth_index, label_candidate_pairs,
    sample_negative_pairs, build_training_matrix,
    train_match_model, evaluate_classifier
)

def run_phase5(train_data: dict, output_dir: Path):
    models_dir = Path("models")
    models_dir.mkdir(parents=True, exist_ok=True)
    
    print("Preprocessing datasets...")
    s1 = apply_preprocessing(train_data["source1"])
    s2 = apply_preprocessing(train_data["source2"])
    s3 = apply_preprocessing(train_data["source3"])
    gt = train_data.get("ground_truth", pd.DataFrame())
    
    print("Creating S1 Entity Split...")
    train_s1, val_s1 = create_entity_split(s1, test_size=0.2, random_state=42)
    print(f"Train S1 Entities: {len(train_s1)}")
    print(f"Validation S1 Entities: {len(val_s1)}")
    
    # Generate Candidates
    print("Generating Training Candidates...")
    train_cands = generate_training_candidates(train_s1, s2, s3)
    
    print("Generating Validation Candidates...")
    val_cands = generate_training_candidates(val_s1, s2, s3)
    
    # Ground Truth
    gt_index = build_ground_truth_index(gt)
    
    print("Labeling Training Candidates...")
    train_pos, train_gt_pos_count, train_missing_pos = label_candidate_pairs(train_cands, gt_index)
    train_recall = len(train_pos) / max(train_gt_pos_count, 1)
    
    print("Sampling Negative Training Candidates...")
    train_neg = sample_negative_pairs(train_cands, gt_index, train_s1, s2, s3, num_random=3, num_hard_name=2, random_state=42)
    
    train_pairs = train_pos + train_neg
    print(f"Train Positive Pairs: {len(train_pos)}")
    print(f"Train Negative Pairs: {len(train_neg)}")
    print(f"Train Candidate Recall: {train_recall:.4f}")
    
    if train_missing_pos > 0:
        print(f"WARNING: {train_missing_pos} positive pairs were NOT generated by blocking.")
        
    print("Labeling Validation Candidates (Using ALL generated candidates)...")
    val_pos, val_gt_pos_count, val_missing_pos = label_candidate_pairs(val_cands, gt_index)
    
    # For validation, we use all generated candidates as negatives
    val_neg = []
    for s1_id, (cands, prov) in val_cands.items():
        true_matches = gt_index.get(s1_id, set())
        for c in cands:
            if c not in true_matches:
                val_neg.append({"s1_id": s1_id, "cand_id": c, "provenance": prov.get(c, []), "label": 0})
                
    val_pairs = val_pos + val_neg
    
    print("Building Feature Matrices...")
    train_df = build_training_matrix(train_pairs, train_s1, s2, s3)
    val_df = build_training_matrix(val_pairs, val_s1, s2, s3)
    
    # Drop non-feature columns
    drop_cols = ['label', 's1_id', 'cand_id', 'candidate_source']
    
    X_train = train_df.drop(columns=drop_cols)
    y_train = train_df['label']
    
    X_val = val_df.drop(columns=drop_cols)
    y_val = val_df['label']
    
    # Verify column match
    assert list(X_train.columns) == list(X_val.columns), "Feature columns mismatch!"
    
    # Leakage check
    for col in X_train.columns:
        assert 'match' not in col.lower(), f"Potential target leakage in feature: {col}"
        
    # Save feature schema
    feature_schema = list(X_train.columns)
    with open(models_dir / "feature_columns.json", "w") as f:
        json.dump(feature_schema, f)
        
    print("Training LightGBM Classifier...")
    model = train_match_model(X_train, y_train, X_val, y_val, random_state=42)
    
    print("Saving Model...")
    model.save_model(models_dir / "lightgbm_matcher.txt")
    
    print("Generating Validation Predictions...")
    val_preds = model.predict(X_val)
    
    val_out_df = pd.DataFrame({
        "source1_entity_id": val_df['s1_id'],
        "candidate_entity_id": val_df['cand_id'],
        "candidate_source": val_df['candidate_source'],
        "label": val_df['label'],
        "match_probability": val_preds
    })
    
    val_out_df = val_out_df.sort_values(by=['source1_entity_id', 'candidate_entity_id'])
    val_out_df.to_csv(output_dir / "validation_predictions.tsv", sep='\t', index=False)
    
    print("Evaluating Model...")
    eval_metrics = evaluate_classifier(y_val, val_preds)
    
    # Feature Importance
    print("Extracting Feature Importance...")
    importance_gain = model.feature_importance(importance_type='gain')
    importance_split = model.feature_importance(importance_type='split')
    
    fi_df = pd.DataFrame({
        "feature": X_train.columns,
        "gain": importance_gain,
        "split": importance_split
    }).sort_values(by="gain", ascending=False)
    
    fi_df.to_csv(output_dir / "feature_importance.csv", index=False)
    
    # Error Analysis
    print("Generating Error Analysis...")
    val_out_df['pred_label'] = (val_out_df['match_probability'] >= 0.5).astype(int)
    
    false_positives = val_out_df[(val_out_df['label'] == 0) & (val_out_df['pred_label'] == 1)].sort_values(by='match_probability', ascending=False)
    false_negatives = val_out_df[(val_out_df['label'] == 1) & (val_out_df['pred_label'] == 0)].sort_values(by='match_probability', ascending=True)
    
    # Meta data save
    metadata = {
        "model_type": "LightGBM Binary Classifier",
        "random_seed": 42,
        "training_row_count": len(train_df),
        "validation_row_count": len(val_df),
        "positive_count_train": int(y_train.sum()),
        "negative_count_train": int(len(y_train) - y_train.sum()),
        "feature_count": len(feature_schema),
        "best_iteration": model.best_iteration,
        "phase5_version": "1.0",
        "candidate_recall": train_recall
    }
    with open(models_dir / "model_metadata.json", "w") as f:
        json.dump(metadata, f, indent=4)
        
    # Write model report
    report_path = output_dir / "model_report.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# Phase 5 — Matching Model Report\n\n")
        f.write("## 1. Objective\n")
        f.write("Train a supervised binary classifier (LightGBM) to distinguish true candidate pairs from non-matches based on normalized features.\n\n")
        
        f.write("## 2. Dataset Construction\n")
        f.write(f"- **Train S1 Entities:** {len(train_s1)}\n")
        f.write(f"- **Validation S1 Entities:** {len(val_s1)}\n")
        f.write(f"- **Train Candidates (Pairs):** {len(train_df)}\n")
        f.write(f"- **Train Positives:** {metadata['positive_count_train']}\n")
        f.write(f"- **Train Negatives:** {metadata['negative_count_train']}\n")
        f.write(f"- **Train Candidate Recall:** {train_recall*100:.2f}%\n\n")
        
        f.write("## 3. Label Construction\n")
        f.write("Candidate pairs are matched against `ground_truth.tsv` via S1 entity matching. Positive labels are given if the S2/S3 entity exists in the ground truth for the given S1. Otherwise, label is 0.\n\n")
        
        f.write("## 4. Negative Sampling\n")
        f.write("For training, negative pairs were systematically sampled. For each S1 entity, we included up to 3 random candidates, and 2 'hard negatives' based on pseudo string similarity against remaining candidates.\n\n")
        
        f.write("## 5. Feature Matrix\n")
        f.write(f"- **Total Features:** {metadata['feature_count']}\n")
        f.write("- **Leakage Check:** Verified no feature column contains 'match' or uses ground truth.\n\n")
        
        f.write("## 6. Model Configuration\n")
        f.write("- **Algorithm:** LightGBM Binary\n")
        f.write("- **Class Imbalance:** `scale_pos_weight` used dynamically.\n")
        f.write(f"- **Best Iteration:** {model.best_iteration}\n\n")
        
        f.write("## 7. Validation Results\n")
        f.write(f"- **ROC-AUC:** {eval_metrics['roc_auc']:.4f}\n")
        f.write(f"- **PR-AUC:** {eval_metrics['pr_auc']:.4f}\n")
        f.write(f"- **Log Loss:** {eval_metrics['log_loss']:.4f}\n")
        f.write("### Reference Threshold (t=0.5)\n")
        f.write(f"- **Precision:** {eval_metrics['ref_precision']:.4f}\n")
        f.write(f"- **Recall:** {eval_metrics['ref_recall']:.4f}\n")
        f.write(f"- **F1-Score:** {eval_metrics['ref_f1']:.4f}\n")
        f.write("### Diagnostic F0.5\n")
        for th, val in eval_metrics['f05_diagnostic'].items():
            f.write(f"- **{th}**: {val:.4f}\n")
        f.write("\n*(Note: Final threshold has NOT yet been selected.)*\n\n")
        
        f.write("## 8. Feature Importance (Top 10)\n")
        for i, row in fi_df.head(10).iterrows():
            f.write(f"- **{row['feature']}**: {row['gain']:.2f}\n")
        f.write("\n")
        
        f.write("## 9. Error Analysis Summary\n")
        f.write(f"- **False Positives (t=0.5):** {len(false_positives)}\n")
        f.write(f"- **False Negatives (t=0.5):** {len(false_negatives)}\n")
        
    print(f"Wrote {report_path}")
    
    # Write model error analysis
    err_path = output_dir / "model_error_analysis.md"
    with open(err_path, "w", encoding="utf-8") as f:
        f.write("# Model Error Analysis\n\n")
        f.write("## Top 10 False Positives (High Confidence, Wrong)\n")
        for _, row in false_positives.head(10).iterrows():
            f.write(f"- **S1:** {row['source1_entity_id']} **Cand:** {row['candidate_entity_id']} ({row['candidate_source']})\n")
            f.write(f"  - Prob: {row['match_probability']:.4f}\n")
            
        f.write("\n## Top 10 False Negatives (Low Confidence, Wrong)\n")
        for _, row in false_negatives.head(10).iterrows():
            f.write(f"- **S1:** {row['source1_entity_id']} **Cand:** {row['candidate_entity_id']} ({row['candidate_source']})\n")
            f.write(f"  - Prob: {row['match_probability']:.4f}\n")
            
    print(f"Wrote {err_path}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-root", type=str, default="dataset")
    parser.add_argument("--output-dir", type=str, default="output")
    args = parser.parse_args()

    data_root = Path(args.data_root)
    train_dir = data_root / "train"
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("Loading training datasets for Phase 5...")
    try:
        train_data = load_train_data(train_dir, TRAIN_FILES)
    except Exception as e:
        print(f"Error loading data: {e}")
        sys.exit(1)
        
    run_phase5(train_data, output_dir)

if __name__ == "__main__":
    main()
