import os
import shutil
import hashlib
import json
import csv
from pathlib import Path
from datetime import datetime

def calculate_sha256(filepath: Path) -> str:
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def init_history_csv(history_path: Path):
    if not history_path.exists():
        with open(history_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                "version", "date", "validation_f0_5", "validation_precision", 
                "validation_recall", "candidate_recall", "threshold", 
                "test_candidate_count", "test_predicted_match_count", 
                "submission_status", "leaderboard_score", "notes"
            ])

def append_history(history_path: Path, row: list):
    with open(history_path, 'a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)

def update_submission_log(log_path: Path, meta: dict):
    mode = 'a' if log_path.exists() else 'w'
    with open(log_path, mode) as f:
        if mode == 'w':
            f.write("# Submission Log\n\n")
        f.write(f"## {meta['version']}\n\n")
        f.write(f"Date: {meta['created_at']}\n")
        f.write(f"Version: {meta['version']}\n")
        f.write(f"Validation F0.5: {meta['validation_f0_5']}\n")
        f.write(f"Validation Precision: {meta['validation_precision']}\n")
        f.write(f"Validation Recall: {meta['validation_recall']}\n")
        f.write(f"Candidate Recall: {meta['candidate_recall']}\n")
        f.write(f"Threshold: {meta['threshold']}\n")
        f.write(f"Leaderboard Score: NOT_AVAILABLE\n")
        f.write(f"Status: {meta['status']}\n")
        f.write(f"Notes: {meta['notes']}\n\n")

def run_versioning(project_root: Path):
    subs_dir = project_root / "submissions"
    subs_dir.mkdir(exist_ok=True)
    
    history_csv = subs_dir / "submission_history.csv"
    submission_log = subs_dir / "submission_log.md"
    init_history_csv(history_csv)
    
    # Determine next version
    existing_versions = [d.name for d in subs_dir.iterdir() if d.is_dir() and d.name.startswith("v")]
    next_v = f"v{len(existing_versions) + 1}"
    
    v_dir = subs_dir / next_v
    v_dir.mkdir(exist_ok=True)
    
    # Locate artifacts
    orig_zip = project_root / "amazon_ml_challenge_submission.zip"
    if not orig_zip.exists():
        print(f"Error: {orig_zip} not found. Run Phase 8 package_submission.py first.")
        return
        
    new_zip = v_dir / f"amazon_ml_challenge_submission_{next_v}.zip"
    shutil.copy2(orig_zip, new_zip)
    
    zip_hash = calculate_sha256(new_zip)
    
    # Load Threshold for metadata
    try:
        with open(project_root / "models" / "final_threshold.json", "r") as f:
            thresh_meta = json.load(f)
        threshold = thresh_meta.get("threshold", 0.0)
    except Exception:
        threshold = "N/A"
        
    meta = {
        "version": next_v,
        "status": "prepared",
        "model": "LightGBM",
        "threshold": threshold,
        "validation_f0_5": "N/A (Pending Data)",
        "validation_precision": "N/A (Pending Data)",
        "validation_recall": "N/A (Pending Data)",
        "candidate_recall": "N/A (Pending Data)",
        "created_at": datetime.now().isoformat(),
        "notes": "Baseline final system" if next_v == "v1" else ""
    }
    
    with open(v_dir / "submission_metadata.json", "w") as f:
        json.dump(meta, f, indent=4)
        
    with open(v_dir / "MANIFEST.md", "w") as f:
        f.write(f"# Submission {next_v}\n\n")
        f.write("## Configuration\n")
        f.write(f"- Model: LightGBM\n")
        f.write(f"- Threshold: {threshold}\n")
        f.write("- Feature count: Dynamically generated by features.py\n")
        f.write("- Blocking configuration: Multi-key\n")
        f.write("- Random seed: 42\n\n")
        f.write("## Validation\n")
        f.write(f"- Precision: {meta['validation_precision']}\n")
        f.write(f"- Recall: {meta['validation_recall']}\n")
        f.write(f"- F0.5: {meta['validation_f0_5']}\n")
        f.write(f"- Candidate recall: {meta['candidate_recall']}\n\n")
        f.write("## Files\n")
        f.write(f"- {new_zip.name}\n")
        f.write("- submission_metadata.json\n")
        f.write("- MANIFEST.md\n\n")
        f.write("## Integrity\n")
        f.write(f"- filename: {new_zip.name}\n")
        f.write(f"- file size: {new_zip.stat().st_size} bytes\n")
        f.write(f"- SHA-256 hash: {zip_hash}\n")

    append_history(history_csv, [
        next_v, meta['created_at'], meta['validation_f0_5'], meta['validation_precision'],
        meta['validation_recall'], meta['candidate_recall'], meta['threshold'],
        "N/A", "N/A", meta['status'], "NOT_AVAILABLE", meta['notes']
    ])
    
    update_submission_log(submission_log, meta)
    
    print(f"Version {next_v} prepared successfully at {v_dir}")
    print(f"ZIP Hash: {zip_hash}")

if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    run_versioning(root)
